### ISSUE TITLE
[PE-D][Tester B] Add-Related Commands Error in Name Input

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W08-3/tp#141]
Add-related commands do not allow input of names with special characters such as "/".

![Screenshot 2022-10-28 at 12.39.50 PM.png](https://raw.githubusercontent.com/jicsontoh/ped/main/files/afa0ecb8-a273-45c7-a8e7-622642bb4bb2.png)

Names with special characters such as "Priya d/o Anandarajah" 

Steps to produce:
1. student n/Priya d/o Anandarajah  y/1 m/CS4226 m/CS5242 m/CS1101S p/98765432 e/JohnD@example.com g/M t/friends t/owesMoney l/UTown Residences git/johnnyd

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jicsontoh/ped#3

**Comment by Jonaspng** [comment]
As stated in UG, we only allow english alphanumerical characters for name
