### ISSUE TITLE
[PE-D][Tester D] White square appears at the intersection of scrollbars 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W08-3/tp#143]
![image.png](https://raw.githubusercontent.com/ruiqi7/ped/main/files/3da9398e-4a1c-4f45-b9e9-29d5207959ac.png)

Just a minor UI issue, but when the message displayed in the result display box is long and over several lines, there seems to be a white square that shows up at the intersection of the vertical and horizontal scroll bars.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: ruiqi7/ped#2

**Comment by Jonaspng** [comment]
I am not sure whether we are allowed to change this as we are not allowed to make any UI related changes in v1.4

**Comment by Jonaspng** [comment]
Wont fix
