### ISSUE TITLE
[PE-D][Tester B] Add-Related Command does not allow Chinese Characters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W08-3/tp#144]
Add-Related Commands such as student, prof, ta does not allow the use of Chinese characters for name

![Screenshot 2022-10-28 at 4.24.11 PM.png](https://raw.githubusercontent.com/jicsontoh/ped/main/files/c750f48d-0d62-47dd-9c83-1c4eaa02d0ed.png)

Steps to produce:
1. student n/小明 y/1 m/CS4226 m/CS5242 m/CS1101S p/98765432 e/JohnD@example.com g/M t/friends t/owesMoney l/UTown Residences git/johnnyd

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jicsontoh/ped#4

**Comment by Jonaspng** [comment]
I dont know what to say. Maybe can update UG to say only only english characters
