### ISSUE TITLE
[PE-D][Tester C] edit rating values: Blank Rating values removes values

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W08-3/tp#165]
![image.png](https://raw.githubusercontent.com/lulucopter/ped/main/files/4c3177b5-b5f7-44cf-a149-a09b2e93ffd3.png)

Similar to the year values, although rating values should not be blank, they are not caught by the application, and instead, it automatically removes the values entirely

![image.png](https://raw.githubusercontent.com/lulucopter/ped/main/files/7614ba44-e5c0-4e64-855f-c442579ba8a7.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: lulucopter/ped#8

**Comment by Jonaspng** [comment]
This feature is purposely designed by us. Tying `git/` without any other input behind the prefix will be thought as clearing the github username field.
