### ISSUE TITLE
[PE-D][Tester D] Incorrect sorting of names by alphabetical order

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W08-3/tp#171]
![image.png](https://raw.githubusercontent.com/ruiqi7/ped/main/files/e696d311-41dc-4171-99ce-7ddc1dad59dd.png)

Steps taken:
1. student n/john y/1 m/cs1101s p/98765432 e/JohnD@example.com g/M
2. student n/Walter y/1 m/CS2100 p/98765432 e/Walter@example.com g/M
3. sort A-Z n/

john should appear before Walter, might be because of the lower case alphabet?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ruiqi7/ped#6

**Comment by GarethOng** [comment]
#199 fixes this issue.
