### ISSUE TITLE
[PE-D][Tester E] Export error when file name ends with "/".

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W08-3/tp#174]
Exporting with "/" characters at end of file name results in error.

![image.png](https://raw.githubusercontent.com/tantzeyeong/ped/main/files/b1102e1b-6830-4e1a-a7bf-015a8ece2373.png)

![image.png](https://raw.githubusercontent.com/tantzeyeong/ped/main/files/095a2916-7744-425f-b367-5a22b28d924f.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: tantzeyeong/ped#5

**Comment by GarethOng** [comment]
fixed by #200 by enforcing a stricter regex that prevents possible bugs when user include multiple / or \ in their file name.
