### ISSUE TITLE
[PE-D][Tester D] Long inputs get cut off

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W08-3/tp#190]
![image.png](https://raw.githubusercontent.com/ruiqi7/ped/main/files/a693c9d8-dd76-4137-9ff7-ec83e208a046.png)

Users probably would not have the need to key in such long inputs in most cases, but this problem will also occur if the user resizes the window width to be smaller. Could consider restricting input length or using ellipsis?

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: ruiqi7/ped#12

**Comment by Jonaspng** [comment]
Not allowed to change UI during 1.4
